import type { EventConfig } from "./types"

const sections = (ids: { id: string; title: string }[]) => ids

export const eventsConfig: EventConfig[] = [
  // January 2026
  {
    slug: "new-year-resource-open-house",
    title: "New Year Resource Open House",
    date: "2026-01-06",
    time: "10:00 AM - 3:00 PM",
    location: "Central Library, Main Branch",
    image: "/resource-fair.jpg",
    description: "Start the year by learning about food assistance, housing support, job training, and health services. Staff from multiple agencies will be on hand to answer questions and help with applications.",
    tags: ["Free"],
    month: "January",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Available resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "winter-job-fair-jan",
    title: "Winter Job Fair",
    date: "2026-01-11",
    time: "9:00 AM - 2:00 PM",
    location: "Downtown Community Center",
    image: "/job-fair-event.jpg",
    description: "Connect with local employers hiring for full-time and part-time positions. Bring copies of your résumé. Interview prep and career coaching available on-site.",
    tags: ["Free"],
    month: "January",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "employers", title: "Participating employers" },
      { id: "prepare", title: "How to prepare" },
    ]),
  },
  {
    slug: "free-legal-clinic-jan",
    title: "Free Legal Advice Clinic",
    date: "2026-01-17",
    time: "1:00 PM - 5:00 PM",
    location: "City Hall Annex, Room 101",
    image: "/legal-clinic.jpg",
    description: "Volunteer attorneys offer free 30-minute consultations on housing, benefits, family law, and consumer issues. No appointment needed; first come, first served.",
    tags: ["Free"],
    month: "January",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics covered" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  {
    slug: "senior-social-jan",
    title: "Senior Social & Resource Day",
    date: "2026-01-27",
    time: "11:00 AM - 2:00 PM",
    location: "North Community Center",
    image: "/senior-wellness.jpg",
    description: "Lunch, bingo, and information about Medicare, nutrition programs, and transportation services for older adults. All seniors welcome.",
    tags: ["Free", "Seniors"],
    month: "January",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "activities", title: "Activities" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // February 2026
  {
    slug: "financial-literacy-feb",
    title: "Financial Literacy Workshop",
    date: "2026-02-02",
    time: "6:00 PM - 8:00 PM",
    location: "Central Library, Meeting Room A",
    image: "/financial-workshop.jpg",
    description: "Learn budgeting, saving, and credit basics. Free workbooks and one-on-one follow-up available. Childcare provided with advance registration.",
    tags: ["Free"],
    month: "February",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "health-screenings-feb",
    title: "Free Health Screenings",
    date: "2026-02-10",
    time: "10:00 AM - 2:00 PM",
    location: "Downtown Community Center",
    image: "/health-fair.jpg",
    description: "Blood pressure, glucose, and cholesterol screenings. Information on low-cost clinics and prescription assistance programs.",
    tags: ["Free"],
    month: "February",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "screenings", title: "Screenings offered" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "housing-resources-feb",
    title: "Housing Resources Fair",
    date: "2026-02-18",
    time: "10:00 AM - 4:00 PM",
    location: "City Hall Lobby",
    image: "/housing-fair.jpg",
    description: "Learn about rental assistance, eviction prevention, affordable housing waitlists, and first-time homebuyer programs. Bilingual staff available.",
    tags: ["Free"],
    month: "February",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "programs", title: "Programs" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  {
    slug: "youth-mentoring-feb",
    title: "Youth Mentoring Info Night",
    date: "2026-02-25",
    time: "5:30 PM - 7:30 PM",
    location: "City Arts Center",
    image: "/youth-arts-showcase.jpg",
    description: "Parents and youth can meet mentors and learn about after-school programs, tutoring, and college readiness resources. Light dinner provided.",
    tags: ["Free", "Family-friendly"],
    month: "February",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "programs", title: "Programs" },
      { id: "register", title: "How to sign up" },
    ]),
  },
  // March 2026
  {
    slug: "tax-help-march",
    title: "Free Tax Preparation (VITA)",
    date: "2026-03-02",
    time: "9:00 AM - 4:00 PM",
    location: "Community Center",
    image: "/tax-help.jpg",
    description: "IRS-certified volunteers provide free tax filing for eligible households. By appointment; bring ID, Social Security cards, and tax documents.",
    tags: ["Free"],
    month: "March",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-bring", title: "What to bring" },
      { id: "appointments", title: "Appointments" },
    ]),
  },
  {
    slug: "women-history-resources",
    title: "Women's History Month Resource Fair",
    date: "2026-03-09",
    time: "11:00 AM - 3:00 PM",
    location: "Central Library",
    image: "/resource-fair.jpg",
    description: "Celebrate Women's History Month with information on childcare, job training, healthcare, and support services for women and families.",
    tags: ["Free"],
    month: "March",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "nutrition-workshop-march",
    title: "Healthy Eating on a Budget",
    date: "2026-03-16",
    time: "6:00 PM - 7:30 PM",
    location: "North Community Center Kitchen",
    image: "/nutrition-workshop.jpg",
    description: "Cooking demo and tips for nutritious, low-cost meals. SNAP eligibility info and sample recipes to take home.",
    tags: ["Free"],
    month: "March",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "recipes", title: "Recipes" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "disability-resources-march",
    title: "Disability Resources & Accessibility Fair",
    date: "2026-03-23",
    time: "10:00 AM - 2:00 PM",
    location: "Downtown Community Center",
    image: "/accessibility-fair.jpg",
    description: "Learn about benefits, employment services, transportation, and adaptive equipment. ASL interpreters and accessible seating available.",
    tags: ["Free"],
    month: "March",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "services", title: "Services" },
      { id: "accessibility", title: "Accessibility" },
    ]),
  },
  // April 2026
  {
    slug: "spring-resource-fair",
    title: "Spring Resource Fair",
    date: "2026-04-04",
    time: "10:00 AM - 2:00 PM",
    location: "Central Library",
    image: "/resource-fair.jpg",
    description: "Learn about available community resources, benefits, and services at our spring fair.",
    tags: ["Free"],
    month: "April",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-expect", title: "What to expect" },
      { id: "location-parking", title: "Location and parking" },
      { id: "register", title: "How to register" },
    ]),
  },
  {
    slug: "community-health-fair",
    title: "Community Health Fair",
    date: "2026-04-12",
    time: "10:00 AM - 4:00 PM",
    location: "Downtown Community Center",
    image: "/health-fair.jpg",
    description: "Free health screenings and flu shots for all ages.",
    tags: ["Free"],
    month: "April",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "screenings", title: "Screenings and services" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "earth-day-cleanup",
    title: "Earth Day Community Cleanup",
    date: "2026-04-19",
    time: "9:00 AM - 12:00 PM",
    location: "City Park and riverfront",
    image: "/earth-day-cleanup.jpg",
    description: "Join neighbors for a morning of litter pickup and park beautification.",
    tags: ["Free", "Family-friendly"],
    month: "April",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-bring", title: "What to bring" },
      { id: "meetup", title: "Meetup locations" },
    ]),
  },
  {
    slug: "community-job-fair",
    title: "Community Job Fair",
    date: "2026-04-26",
    time: "9:00 AM - 3:00 PM",
    location: "Central Community Center",
    image: "/job-fair-event.jpg",
    description: "Meet with 50+ employers hiring now.",
    tags: ["Free"],
    month: "April",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "employers", title: "Participating employers" },
      { id: "prepare", title: "How to prepare" },
    ]),
  },
  // May 2026
  {
    slug: "youth-arts-showcase",
    title: "Youth Arts Showcase",
    date: "2026-05-03",
    time: "2:00 PM - 6:00 PM",
    location: "City Arts Center",
    image: "/youth-arts-showcase.jpg",
    description: "Celebrate young artists with live performances, exhibits, and hands-on activities.",
    tags: ["Free", "Family-friendly"],
    month: "May",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "schedule", title: "Schedule" },
      { id: "participate", title: "How to participate" },
    ]),
  },
  {
    slug: "tax-help-workshop",
    title: "Tax Preparation Help",
    date: "2026-05-08",
    time: "9:00 AM - 5:00 PM",
    location: "Community Center",
    image: "/tax-help.jpg",
    description: "Free tax preparation assistance for families.",
    tags: ["Free"],
    month: "May",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-bring", title: "What to bring" },
      { id: "appointments", title: "Appointments" },
    ]),
  },
  {
    slug: "senior-wellness-day",
    title: "Senior Wellness Day",
    date: "2026-05-16",
    time: "10:00 AM - 2:00 PM",
    location: "North Community Center",
    image: "/senior-wellness.jpg",
    description: "Health screenings, nutrition tips, and resource connections for older adults.",
    tags: ["Free", "Seniors"],
    month: "May",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "activities", title: "Activities" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "memorial-day-veterans-resources",
    title: "Veterans & Military Family Resource Fair",
    date: "2026-05-22",
    time: "10:00 AM - 2:00 PM",
    location: "Veterans Memorial Hall",
    image: "/veterans-fair.jpg",
    description: "Benefits, employment, housing, and mental health resources for veterans and their families. VA reps and community organizations on site.",
    tags: ["Free"],
    month: "May",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // June 2026
  {
    slug: "summer-youth-kickoff",
    title: "Summer Youth Program Kickoff",
    date: "2026-06-01",
    time: "4:00 PM - 7:00 PM",
    location: "City Park Pavilion",
    image: "/youth-arts-showcase.jpg",
    description: "Register for summer camps, sports, arts, and job programs. Free activities for kids and information for parents.",
    tags: ["Free", "Family-friendly"],
    month: "June",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "programs", title: "Programs" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "housing-rights-workshop-june",
    title: "Tenant Rights Workshop",
    date: "2026-06-09",
    time: "6:00 PM - 8:00 PM",
    location: "Central Library",
    image: "/housing-fair.jpg",
    description: "Know your rights: leases, repairs, eviction process, and where to get help. Presented by legal aid and housing counselors.",
    tags: ["Free"],
    month: "June",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics" },
      { id: "resources", title: "Resources" },
    ]),
  },
  {
    slug: "food-pantry-open-house-june",
    title: "Food Pantry Open House",
    date: "2026-06-14",
    time: "11:00 AM - 3:00 PM",
    location: "Community Food Bank, Main Distribution Center",
    image: "/food-pantry.jpg",
    description: "Tour the facility, learn about eligibility and hours, and pick up fresh produce. SNAP sign-up assistance available.",
    tags: ["Free"],
    month: "June",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "eligibility", title: "Eligibility" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "mental-health-resources-june",
    title: "Mental Health Resources Fair",
    date: "2026-06-25",
    time: "10:00 AM - 2:00 PM",
    location: "Downtown Community Center",
    image: "/health-fair.jpg",
    description: "Information on counseling, support groups, crisis services, and low-cost mental health care. All ages welcome.",
    tags: ["Free"],
    month: "June",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "services", title: "Services" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // July 2026
  {
    slug: "independence-day-community-bbq",
    title: "Community BBQ & Resource Tent",
    date: "2026-07-04",
    time: "12:00 PM - 5:00 PM",
    location: "City Park",
    image: "/community-bbq.jpg",
    description: "Free family BBQ with games and music. Stop by the resource tent for information on summer programs, cooling centers, and emergency assistance.",
    tags: ["Free", "Family-friendly"],
    month: "July",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "activities", title: "Activities" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "esl-and-citizenship-july",
    title: "ESL & Citizenship Information Session",
    date: "2026-07-08",
    time: "6:00 PM - 8:00 PM",
    location: "Central Library",
    image: "/esl-citizenship.jpg",
    description: "Free English classes and citizenship preparation. Learn about eligibility, class schedules, and legal resources. Multiple languages spoken.",
    tags: ["Free"],
    month: "July",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "classes", title: "Classes" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "cooling-center-open-house",
    title: "Cooling Center & Summer Safety",
    date: "2026-07-15",
    time: "10:00 AM - 2:00 PM",
    location: "North Community Center",
    image: "/cooling-center.jpg",
    description: "Learn where to stay cool during heat waves. Free water, sunscreen, and information on utility assistance and cooling center hours.",
    tags: ["Free"],
    month: "July",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "locations", title: "Locations" },
      { id: "resources", title: "Resources" },
    ]),
  },
  {
    slug: "back-to-school-fair-july",
    title: "Back-to-School Resource Fair",
    date: "2026-07-28",
    time: "10:00 AM - 3:00 PM",
    location: "Downtown Community Center",
    image: "/resource-fair.jpg",
    description: "School supplies, backpack giveaways, immunization info, and registration help for the new school year. Proof of residency may be required.",
    tags: ["Free", "Family-friendly"],
    month: "July",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-bring", title: "What to bring" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // August 2026
  {
    slug: "back-to-school-august",
    title: "Back-to-School Health & Wellness",
    date: "2026-08-02",
    time: "9:00 AM - 1:00 PM",
    location: "Central Library",
    image: "/health-fair.jpg",
    description: "Immunizations, sports physicals, vision screenings, and nutrition resources for students. Some services by appointment.",
    tags: ["Free", "Family-friendly"],
    month: "August",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "services", title: "Services" },
      { id: "appointments", title: "Appointments" },
    ]),
  },
  {
    slug: "job-readiness-august",
    title: "Job Readiness Workshop",
    date: "2026-08-11",
    time: "10:00 AM - 12:30 PM",
    location: "Community Center",
    image: "/job-fair-event.jpg",
    description: "Résumé tips, interview practice, and dress-for-success guidance. One-on-one coaching available. All skill levels welcome.",
    tags: ["Free"],
    month: "August",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "senior-lunch-august",
    title: "Senior Lunch & Learn",
    date: "2026-08-19",
    time: "12:00 PM - 2:00 PM",
    location: "North Community Center",
    image: "/senior-wellness.jpg",
    description: "Free lunch and presentation on Medicare updates, prescription savings, and fall prevention. Reservations requested.",
    tags: ["Free", "Seniors"],
    month: "August",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics" },
      { id: "reservations", title: "Reservations" },
    ]),
  },
  {
    slug: "legal-clinic-august",
    title: "Free Legal Clinic",
    date: "2026-08-25",
    time: "2:00 PM - 6:00 PM",
    location: "City Hall Annex",
    image: "/legal-clinic.jpg",
    description: "Free legal consultations on housing, consumer issues, and public benefits. Walk-in; first come, first served.",
    tags: ["Free"],
    month: "August",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics covered" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  // September 2026
  {
    slug: "labor-day-job-fair",
    title: "Labor Day Job Fair",
    date: "2026-09-01",
    time: "9:00 AM - 3:00 PM",
    location: "Central Community Center",
    image: "/job-fair-event.jpg",
    description: "Employers from retail, healthcare, and trades hiring on the spot. Bring ID and résumés. Childcare available with advance notice.",
    tags: ["Free"],
    month: "September",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "employers", title: "Employers" },
      { id: "prepare", title: "How to prepare" },
    ]),
  },
  {
    slug: "financial-coaching-sept",
    title: "Financial Coaching Open House",
    date: "2026-09-06",
    time: "5:30 PM - 7:30 PM",
    location: "Central Library",
    image: "/financial-workshop.jpg",
    description: "Meet financial coaches for free one-on-one sessions on budgeting, debt, and saving. Sign up for ongoing coaching.",
    tags: ["Free"],
    month: "September",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "services", title: "Services" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "hispanic-heritage-resources",
    title: "Hispanic Heritage Month Resource Fair",
    date: "2026-09-14",
    time: "11:00 AM - 4:00 PM",
    location: "Downtown Community Center",
    image: "/resource-fair.jpg",
    description: "Celebrate Hispanic Heritage Month with information on education, health, immigration, and business resources. Bilingual staff and refreshments.",
    tags: ["Free"],
    month: "September",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "domestic-violence-resources-sept",
    title: "Domestic Violence Awareness & Resources",
    date: "2026-09-22",
    time: "6:00 PM - 8:00 PM",
    location: "North Community Center (private room)",
    image: "/dv-resources.jpg",
    description: "Confidential information on shelters, legal protection, counseling, and safety planning. Advocates and referral specialists on site.",
    tags: ["Free"],
    month: "September",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "confidentiality", title: "Confidentiality" },
    ]),
  },
  // October 2026
  {
    slug: "fall-resource-fair-oct",
    title: "Fall Community Resource Fair",
    date: "2026-10-03",
    time: "10:00 AM - 3:00 PM",
    location: "Central Library",
    image: "/resource-fair.jpg",
    description: "One-stop shop for housing, food, health, employment, and education resources. Bring questions and documents for on-site assistance.",
    tags: ["Free"],
    month: "October",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "medicare-open-enrollment",
    title: "Medicare Open Enrollment Info",
    date: "2026-10-11",
    time: "10:00 AM - 2:00 PM",
    location: "North Community Center",
    image: "/senior-wellness.jpg",
    description: "SHIP counselors explain Medicare options, Part D, and supplemental plans. One-on-one help with comparing plans. Appointments recommended.",
    tags: ["Free", "Seniors"],
    month: "October",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "what-to-bring", title: "What to bring" },
      { id: "appointments", title: "Appointments" },
    ]),
  },
  {
    slug: "halloween-family-resources",
    title: "Halloween Family Resource Day",
    date: "2026-10-19",
    time: "4:00 PM - 7:00 PM",
    location: "City Park Pavilion",
    image: "/youth-arts-showcase.jpg",
    description: "Safe trick-or-treating, games, and resource tables for families. Information on childcare, after-school programs, and family support.",
    tags: ["Free", "Family-friendly"],
    month: "October",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "activities", title: "Activities" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "veterans-resources-oct",
    title: "Veterans Resource Roundtable",
    date: "2026-10-26",
    time: "6:00 PM - 8:00 PM",
    location: "Veterans Memorial Hall",
    image: "/veterans-fair.jpg",
    description: "VA benefits, employment, housing, and mental health resources. Open to veterans and family members. No registration required.",
    tags: ["Free"],
    month: "October",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // November 2026
  {
    slug: "thanksgiving-food-assistance",
    title: "Thanksgiving Food Distribution",
    date: "2026-11-02",
    time: "9:00 AM - 12:00 PM",
    location: "Community Food Bank",
    image: "/food-pantry.jpg",
    description: "Free turkey and fixings for eligible families. Pre-registration required. Bring ID and proof of address.",
    tags: ["Free"],
    month: "November",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "eligibility", title: "Eligibility" },
      { id: "register", title: "Registration" },
    ]),
  },
  {
    slug: "health-screenings-nov",
    title: "Fall Health Screenings",
    date: "2026-11-10",
    time: "10:00 AM - 2:00 PM",
    location: "Downtown Community Center",
    image: "/health-fair.jpg",
    description: "Blood pressure, glucose, flu shots, and COVID boosters. Information on low-cost clinics and prescription programs.",
    tags: ["Free"],
    month: "November",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "screenings", title: "Screenings" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "housing-help-nov",
    title: "Housing & Eviction Prevention Workshop",
    date: "2026-11-17",
    time: "6:00 PM - 8:00 PM",
    location: "Central Library",
    image: "/housing-fair.jpg",
    description: "Learn about rental assistance, emergency funds, and legal help to avoid eviction. One-on-one intake available.",
    tags: ["Free"],
    month: "November",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "programs", title: "Programs" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  {
    slug: "senior-holiday-lunch-nov",
    title: "Senior Holiday Lunch",
    date: "2026-11-24",
    time: "11:30 AM - 2:00 PM",
    location: "North Community Center",
    image: "/senior-wellness.jpg",
    description: "Free Thanksgiving lunch for seniors. Entertainment and information on winter safety and heating assistance.",
    tags: ["Free", "Seniors"],
    month: "November",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "reservations", title: "Reservations" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  // December 2026
  {
    slug: "winter-resource-fair-dec",
    title: "Winter Resource Fair",
    date: "2026-12-01",
    time: "10:00 AM - 3:00 PM",
    location: "Central Library",
    image: "/resource-fair.jpg",
    description: "Heating assistance, shelter info, food resources, and holiday programs. Get connected before the cold season.",
    tags: ["Free"],
    month: "December",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
  {
    slug: "toy-drive-pickup-dec",
    title: "Holiday Toy Drive Distribution",
    date: "2026-12-07",
    time: "9:00 AM - 4:00 PM",
    location: "Downtown Community Center",
    image: "/toy-drive.jpg",
    description: "Pre-registered families can pick up toys and books for children. Proof of registration and ID required.",
    tags: ["Free", "Family-friendly"],
    month: "December",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "registration", title: "Registration" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  {
    slug: "legal-clinic-dec",
    title: "Year-End Legal Clinic",
    date: "2026-12-15",
    time: "1:00 PM - 5:00 PM",
    location: "City Hall Annex",
    image: "/legal-clinic.jpg",
    description: "Free legal advice on housing, benefits, and consumer issues. Walk-in; first come, first served.",
    tags: ["Free"],
    month: "December",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "topics", title: "Topics" },
      { id: "what-to-bring", title: "What to bring" },
    ]),
  },
  {
    slug: "new-year-readiness-dec",
    title: "New Year Readiness Open House",
    date: "2026-12-29",
    time: "10:00 AM - 2:00 PM",
    location: "Community Center",
    image: "/resource-fair.jpg",
    description: "Get a head start on 2027: job training, tax prep sign-up, benefits renewal, and housing resources. Light refreshments.",
    tags: ["Free"],
    month: "December",
    year: 2026,
    sections: sections([
      { id: "overview", title: "Overview" },
      { id: "resources", title: "Resources" },
      { id: "location-parking", title: "Location and parking" },
    ]),
  },
]

export function getEventBySlug(slug: string): EventConfig | undefined {
  return eventsConfig.find((e) => e.slug === slug)
}

export function getEventSlugs(): string[] {
  return eventsConfig.map((e) => e.slug)
}

/** Events in the shape expected by carousel/hero (with id). */
export function getUpcomingEvents(): Array<EventConfig & { id: number }> {
  return eventsConfig.map((ev, i) => ({ ...ev, id: i + 1 }))
}
