export interface Resource {
  id: string
  name: string
  category: string
  description: string
  address: string
  phone: string
  email: string
  website: string
  tags: string[]
  hours: string
  distance?: number
  isFree: boolean
  ageGroups: string[]
  featured?: boolean
  image?: string
}

export const allResources: Resource[] = [
  {
    id: "1",
    name: "Downtown Community Center",
    category: "Youth Programs",
    description: "Offering after-school programs, sports, arts, and mentoring for youth ages 6-18.",
    address: "123 Main Street, Downtown",
    phone: "(206) 555-0100",
    email: "info@dtcc.org",
    website: "https://www.ymca.org",
    tags: ["Youth", "Sports", "Arts", "Free"],
    hours: "Mon-Fri 3pm-8pm, Sat 10am-6pm",
    distance: 0.5,
    isFree: true,
    ageGroups: ["Teens", "Families"],
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&h=800&fit=crop",
  },
  {
    id: "2",
    name: "Mill Creek Food Bank",
    category: "Food",
    description: "Emergency food assistance and nutrition programs for residents in need.",
    address: "456 Oak Avenue",
    phone: "(206) 555-0101",
    email: "help@cityfoodbank.org",
    website: "https://www.feedingamerica.org",
    tags: ["Food", "Free", "Emergency"],
    hours: "Mon-Sat 9am-5pm",
    distance: 1.2,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&h=800&fit=crop",
  },
  {
    id: "3",
    name: "Community Mental Health Services",
    category: "Mental Health",
    description: "Counseling, therapy, and crisis support services for all ages.",
    address: "789 Pine Street",
    phone: "(206) 555-0102",
    email: "support@cmhs.org",
    website: "https://www.nami.org",
    tags: ["Mental Health", "Counseling", "Support"],
    hours: "Mon-Fri 8am-6pm, Sat 10am-4pm",
    distance: 0.8,
    isFree: false,
    ageGroups: ["Teens", "Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=800&fit=crop",
  },
  {
    id: "4",
    name: "Senior Housing Initiative",
    category: "Housing",
    description: "Affordable housing options and support services specifically for seniors.",
    address: "321 Elm Street",
    phone: "(206) 555-0103",
    email: "info@seniorhousing.org",
    website: "https://www.hud.gov",
    tags: ["Housing", "Seniors", "Affordable"],
    hours: "Mon-Fri 9am-5pm",
    distance: 2.1,
    isFree: false,
    ageGroups: ["Seniors"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=800&fit=crop",
  },
  {
    id: "5",
    name: "Youth Scholarship Fund",
    category: "Education",
    description: "Educational scholarships and mentoring programs for youth from underserved communities.",
    address: "555 Birch Road",
    phone: "(206) 555-0104",
    email: "scholarships@ysf.org",
    website: "https://www.fastweb.com",
    tags: ["Education", "Youth", "Scholarships", "Free"],
    hours: "Mon-Fri 10am-6pm",
    distance: 1.5,
    isFree: true,
    ageGroups: ["Teens"],
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=800&fit=crop",
  },
  {
    id: "6",
    name: "Emergency Assistance Hotline",
    category: "Financial Aid",
    description: "Financial assistance, rent support, and utility bill help for qualified residents.",
    address: "Online & Phone",
    phone: "(206) 555-0105",
    email: "aid@emergencyassist.org",
    website: "https://www.211.org",
    tags: ["Financial Aid", "Emergency", "Utilities", "Free"],
    hours: "24/7",
    distance: 0,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=800&fit=crop",
  },
  {
    id: "7",
    name: "Healthcare for All Clinic",
    category: "Healthcare",
    description: "Free and low-cost medical services including preventive care and vaccinations.",
    address: "234 Wellness Lane",
    phone: "(206) 555-0106",
    email: "care@healthcareforall.org",
    website: "https://findahealthcenter.hrsa.gov",
    tags: ["Healthcare", "Low-cost", "Vaccines"],
    hours: "Mon-Fri 8am-5pm, Sat 10am-2pm",
    distance: 0.9,
    isFree: false,
    ageGroups: ["Families", "Seniors", "Teens"],
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=800&fit=crop",
  },
  {
    id: "8",
    name: "Job Training Academy",
    category: "Employment",
    description: "Professional skills training and job placement assistance for all ages.",
    address: "888 Career Boulevard",
    phone: "(206) 555-0107",
    email: "enroll@jobtraining.org",
    website: "https://www.careeronestop.org",
    tags: ["Employment", "Training", "Free"],
    hours: "Mon-Fri 9am-6pm, Sat 10am-3pm",
    distance: 1.8,
    isFree: true,
    ageGroups: ["Teens", "Families"],
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=800&fit=crop",
  },
  {
    id: "9",
    name: "Community Legal Aid",
    category: "Legal Services",
    description: "Free legal advice, eviction defense, and assistance with immigration, benefits, and family law.",
    address: "100 Justice Way",
    phone: "(206) 555-0108",
    email: "help@communitylegalaid.org",
    website: "https://www.lawhelp.org",
    tags: ["Legal", "Free", "Housing", "Immigration"],
    hours: "Mon-Fri 9am-5pm",
    distance: 1.1,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=800&fit=crop",
  },
]
