export interface Resource {
  id: string
  name: string
  category: string
  description: string
  address: string
  phone: string
  email: string
  website: string
  tags: string[]
  hours: string
  distance?: number
  isFree: boolean
  ageGroups: string[]
  featured?: boolean
  image?: string
}

export const allResources: Resource[] = [
  {
    id: "1",
    name: "Resource Center Alpha",
    category: "Youth Programs",
    description: "Offering after-school programs, sports, arts, and mentoring for youth.",
    address: "123 Example Boulevard",
    phone: "(555) 123-4567",
    email: "alpha@example.com",
    website: "https://example.com/alpha",
    tags: ["Youth", "Sports", "Arts", "Free"],
    hours: "Mon-Fri 3pm-8pm, Sat 10am-6pm",
    distance: 0.5,
    isFree: true,
    ageGroups: ["Teens", "Families"],
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&h=800&fit=crop",
  },
  {
    id: "2",
    name: "Food Assistance Hub",
    category: "Food",
    description: "Emergency food assistance and nutrition programs for residents.",
    address: "456 Sample Avenue",
    phone: "(555) 234-5678",
    email: "food@example.com",
    website: "https://example.com/food",
    tags: ["Food", "Free", "Emergency"],
    hours: "Mon-Sat 9am-5pm",
    distance: 1.2,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&h=800&fit=crop",
  },
  {
    id: "3",
    name: "Mental Health Network",
    category: "Mental Health",
    description: "Counseling, therapy, and crisis support services for all ages.",
    address: "789 Mock Street",
    phone: "(555) 345-6789",
    email: "mentalhealth@example.com",
    website: "https://example.com/health",
    tags: ["Mental Health", "Counseling", "Support"],
    hours: "Mon-Fri 8am-6pm, Sat 10am-4pm",
    distance: 0.8,
    isFree: false,
    ageGroups: ["Teens", "Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=800&fit=crop",
  },
  {
    id: "4",
    name: "Senior Housing Support",
    category: "Housing",
    description: "Affordable housing options and support services specifically for seniors.",
    address: "321 Placeholder Elm",
    phone: "(555) 456-7890",
    email: "housing@example.com",
    website: "https://example.com/housing",
    tags: ["Housing", "Seniors", "Affordable"],
    hours: "Mon-Fri 9am-5pm",
    distance: 2.1,
    isFree: false,
    ageGroups: ["Seniors"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=800&fit=crop",
  },
  {
    id: "5",
    name: "Education Access Initiative",
    category: "Education",
    description: "Educational scholarships and mentoring programs for youth.",
    address: "555 Birch Road",
    phone: "(555) 567-8901",
    email: "education@example.com",
    website: "https://example.com/edu",
    tags: ["Education", "Youth", "Scholarships", "Free"],
    hours: "Mon-Fri 10am-6pm",
    distance: 1.5,
    isFree: true,
    ageGroups: ["Teens"],
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=800&fit=crop",
  },
  {
    id: "6",
    name: "Emergency Care Helpline",
    category: "Financial Aid",
    description: "Financial assistance, rent support, and utility bill help.",
    address: "Online & Phone",
    phone: "(555) 678-9012",
    email: "emergency@example.com",
    website: "https://example.com/emergency",
    tags: ["Financial Aid", "Emergency", "Utilities", "Free"],
    hours: "24/7",
    distance: 0,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=800&fit=crop",
  },
  {
    id: "7",
    name: "Health Clinic Placeholder",
    category: "Healthcare",
    description: "Free and low-cost medical services including preventive care.",
    address: "234 Wellness Lane",
    phone: "(555) 789-0123",
    email: "clinic@example.com",
    website: "https://example.com/clinic",
    tags: ["Healthcare", "Low-cost", "Vaccines"],
    hours: "Mon-Fri 8am-5pm, Sat 10am-2pm",
    distance: 0.9,
    isFree: false,
    ageGroups: ["Families", "Seniors", "Teens"],
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=800&fit=crop",
  },
  {
    id: "8",
    name: "Job Skills Academy",
    category: "Employment",
    description: "Professional skills training and job placement assistance.",
    address: "888 Career Boulevard",
    phone: "(555) 890-1234",
    email: "jobs@example.com",
    website: "https://example.com/jobs",
    tags: ["Employment", "Training", "Free"],
    hours: "Mon-Fri 9am-6pm, Sat 10am-3pm",
    distance: 1.8,
    isFree: true,
    ageGroups: ["Teens", "Families"],
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=800&fit=crop",
  },
  {
    id: "9",
    name: "Legal Rights Clinic",
    category: "Legal Services",
    description: "Free legal advice, eviction defense, and assistance with law.",
    address: "100 Justice Way",
    phone: "(555) 901-2345",
    email: "legal@example.com",
    website: "https://example.com/legal",
    tags: ["Legal", "Free", "Housing", "Immigration"],
    hours: "Mon-Fri 9am-5pm",
    distance: 1.1,
    isFree: true,
    ageGroups: ["Families", "Seniors"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=800&fit=crop",
  },
]
