// Sample data for all homepage sections

export const latestNews = [
  {
    id: 1,
    title: "Mayor Releases 2025 Budget with Focus on Community Services",
    excerpt:
      "The new budget prioritizes funding for youth programs, mental health services, and affordable housing initiatives.",
    date: "November 22, 2025",
    category: "Government",
    image: "/city-government-meeting.jpg",
    link: "/news/mayor-budget-2025",
  },
  {
    id: 2,
    title: "Free Healthcare Services Now Available in Downtown Community Center",
    excerpt: "Residents can access free health screenings, vaccinations, and counseling services starting next week.",
    date: "November 20, 2025",
    category: "Health",
    image: "/healthcare-services.jpg",
    link: "/news/healthcare-services",
  },
  {
    id: 3,
    title: "Youth Employment Program Expands to Five New Neighborhoods",
    excerpt: "The city's job training initiative now serves over 2,000 young adults with job placement support.",
    date: "November 18, 2025",
    category: "Youth",
    image: "/youth-employment.jpg",
    link: "/news/youth-employment",
  },
]

export const popularServices = [
  { id: 1, name: "Apply for Assistance", icon: "ClipboardList", description: "Food, housing, financial aid" },
  { id: 2, name: "Report a Problem", icon: "AlertTriangle", description: "Potholes, graffiti, waste" },
  { id: 3, name: "Pay Bills Online", icon: "CreditCard", description: "Utilities, parking, fines" },
  { id: 4, name: "Schedule Appointments", icon: "Calendar", description: "Permits, licenses, services" },
  { id: 5, name: "Find Nearby Resources", icon: "MapPin", description: "Food, housing, jobs" },
  { id: 6, name: "Access Job Training", icon: "Briefcase", description: "Skills, employment, mentoring" },
  { id: 7, name: "View Event Calendar", icon: "CalendarDays", description: "Community, culture, sports" },
  { id: 8, name: "Get Legal Help", icon: "Scale", description: "Free consultations available" },
]

export const upcomingEvents = [
  // November 2025
  {
    id: 1,
    title: "Thanksgiving Food Drive",
    date: "2025-11-23",
    time: "9:00 AM - 5:00 PM",
    location: "City Food Bank",
    image: "/thanksgiving-food-drive.jpg",
    description: "Help distribute Thanksgiving meals to families in need.",
    tags: [],
    month: "November",
    year: 2025,
  },
  {
    id: 2,
    title: "Community Health Fair",
    date: "2025-11-30",
    time: "10:00 AM - 4:00 PM",
    location: "Downtown Community Center",
    image: "/health-fair.jpg",
    description: "Free health screenings and flu shots for all ages.",
    tags: [],
    month: "November",
    year: 2025,
  },
  // December 2025
  {
    id: 3,
    title: "Winter Coat Distribution",
    date: "2025-12-01",
    time: "10:00 AM - 6:00 PM",
    location: "Multiple locations citywide",
    image: "/winter-coat-giveaway.jpg",
    description: "Free warm coats for families in need.",
    tags: ["Done"],
    month: "December",
    year: 2025,
  },
  {
    id: 4,
    title: "Community Job Fair",
    date: "2025-12-05",
    time: "9:00 AM - 3:00 PM",
    location: "Central Community Center",
    image: "/job-fair-event.jpg",
    description: "Meet with 50+ employers hiring now.",
    tags: ["Free"],
    month: "December",
    year: 2025,
  },
  {
    id: 5,
    title: "Holiday Celebration",
    date: "2025-12-15",
    time: "2:00 PM - 6:00 PM",
    location: "City Park",
    image: "/holiday-celebration.jpg",
    description: "Family celebration with crafts, music, and hot chocolate.",
    tags: ["Free"],
    month: "December",
    year: 2025,
  },
  // January 2026
  {
    id: 6,
    title: "New Year Resource Fair",
    date: "2026-01-10",
    time: "10:00 AM - 2:00 PM",
    location: "Central Library",
    image: "/resource-fair.jpg",
    description: "Learn about available community resources.",
    tags: [],
    month: "January",
    year: 2026,
  },
  {
    id: 7,
    title: "Tax Preparation Help",
    date: "2026-01-25",
    time: "9:00 AM - 5:00 PM",
    location: "Community Center",
    image: "/tax-help.jpg",
    description: "Free tax preparation assistance for families.",
    tags: ["Free"],
    month: "January",
    year: 2026,
  },
  // February 2026
  {
    id: 8,
    title: "Heart Health Day",
    date: "2026-02-14",
    time: "9:00 AM - 3:00 PM",
    location: "Health Center",
    image: "/heart-health.jpg",
    description: "Free heart health screenings and wellness education.",
    tags: ["Free"],
    month: "February",
    year: 2026,
  },
  {
    id: 9,
    title: "Job Skills Training",
    date: "2026-02-20",
    time: "6:00 PM - 8:00 PM",
    location: "Employment Center",
    image: "/job-training.jpg",
    description: "Resume building and interview skills workshop.",
    tags: ["Free"],
    month: "February",
    year: 2026,
  },
]

export const governmentUpdates = [
  {
    id: 1,
    title: "Winter Weather Preparedness",
    subtitle: "City services ready for snow and ice",
    description: "The city is fully prepared with salt, sand, and plow crews ready for winter conditions.",
    date: "Posted November 22, 2025",
    image: "/winter-weather-preparation.jpg",
    action: "Learn More",
  },
  {
    id: 2,
    title: "New Community Center Opens",
    subtitle: "State-of-the-art facility serving east side",
    description: "Brand new recreational and educational facility with pools, gyms, and classrooms.",
    date: "Posted November 20, 2025",
    image: "/new-community-center.jpg",
    action: "Visit Page",
  },
  {
    id: 3,
    title: "Updated Transit Routes",
    subtitle: "Efficient service to new neighborhoods",
    description: "Bus and transit routes expanded to better serve growing residential areas.",
    date: "Posted November 19, 2025",
    image: "/public-transit.jpg",
    action: "See Map",
  },
  {
    id: 4,
    title: "Education Funding Announcement",
    subtitle: "Increased investment in public schools",
    description: "Additional $50M allocated for school improvements and teacher recruitment.",
    date: "Posted November 18, 2025",
    image: "/education-funding.jpg",
    action: "Details",
  },
]

export const benefitPrograms = [
  {
    id: 1,
    title: "Food Assistance",
    description: "Meals, groceries, and nutritional support for families and seniors.",
    eligibility: "Low-income families, seniors, individuals in crisis",
  },
  {
    id: 2,
    title: "Housing Support",
    description: "Emergency housing, rental assistance, and permanent housing programs.",
    eligibility: "Low-income, unhoused, families at risk",
  },
  {
    id: 3,
    title: "Healthcare Services",
    description: "Free and low-cost medical, dental, and mental health services.",
    eligibility: "Uninsured and underinsured residents",
  },
  {
    id: 4,
    title: "Youth Programs",
    description: "Job training, mentoring, education, and recreational activities.",
    eligibility: "Youth ages 13-24 in the city",
  },
]

export const communityStats = [
  {
    number: "100+",
    label: "Resources Listed",
    description: "Comprehensive directory of vetted community services",
    icon: "📋",
  },
  {
    number: "8",
    label: "Service Categories",
    description: "From food to employment assistance",
    icon: "🏷️",
  },
  {
    number: "50+",
    label: "Community Partners",
    description: "Organizations dedicated to serving residents",
    icon: "🤝",
  },
  {
    number: "24/7",
    label: "Support Available",
    description: "Crisis services and emergency assistance anytime",
    icon: "⏰",
  },
]

export const highlightedResources = [
  {
    id: 1,
    title: "City Food Bank",
    category: "Food Assistance",
    shortDescription: "Emergency meals and groceries",
    description:
      "Access emergency food assistance and meal programs across the community with free groceries delivered weekly.",
    image: "/placeholder.svg?key=highlight1",
    location: "Multiple Locations",
    served: "2,000+ families/month",
    tags: ["Free", "Food", "Families"],
  },
  {
    id: 2,
    title: "Youth Development Center",
    category: "Youth Programs",
    shortDescription: "Mentoring and career prep",
    description: "After-school programs, mentoring, career development workshops, and internship placements for teens.",
    image: "/placeholder.svg?key=highlight2",
    location: "3 Community Centers",
    served: "500+ youth annually",
    tags: ["Youth", "Education", "Free"],
  },
  {
    id: 3,
    title: "Community Health Clinic",
    category: "Healthcare",
    shortDescription: "Affordable health services",
    description: "Affordable healthcare services for uninsured and underinsured residents including preventive care.",
    image: "/placeholder.svg?key=highlight3",
    location: "Downtown & North Branch",
    served: "5,000+ patients/year",
    tags: ["Healthcare", "Low-cost", "All Ages"],
  },
]

export const featuredServices = [
  {
    id: 1,
    name: "Food Assistance",
    icon: "Users",
    description: "Emergency meals & groceries",
    category: "Food",
    count: "12 resources",
  },
  {
    id: 2,
    name: "Housing Support",
    icon: "Home",
    description: "Affordable housing & rentals",
    category: "Housing",
    count: "8 resources",
  },
  {
    id: 3,
    name: "Financial Aid",
    icon: "DollarSign",
    description: "Emergency assistance & bills",
    category: "Financial Aid",
    count: "6 resources",
  },
  {
    id: 4,
    name: "Mental Health",
    icon: "Heart",
    description: "Counseling & support services",
    category: "Mental Health",
    count: "9 resources",
  },
  {
    id: 5,
    name: "Education",
    icon: "BookOpen",
    description: "Learning & skill development",
    category: "Education",
    count: "10 resources",
  },
  {
    id: 6,
    name: "Employment",
    icon: "Briefcase",
    description: "Jobs & training programs",
    category: "Employment",
    count: "7 resources",
  },
]

export const featuredCarouselResources = [
  {
    id: "1",
    name: "Downtown Community Center",
    category: "Youth Programs",
    description: "Offering comprehensive after-school programs, sports, arts, and mentoring for youth ages 6-18.",
    shortDescription: "Resource of the Month",
    address: "123 Main Street, Downtown",
    phone: "(206) 555-0100",
    website: "www.dtcc.org",
    image: "/placeholder.svg?key=carousel1",
    tags: ["Youth", "Sports", "Arts", "Free"],
    ageGroups: ["Teens", "Families"],
    hours: "Mon-Fri 3pm-8pm, Sat 10am-6pm",
    whyImportant:
      "This center serves over 500 youth annually, providing safe spaces for learning, recreation, and community building. They focus on underserved neighborhoods.",
  },
  {
    id: "2",
    name: "City Food Bank",
    category: "Food",
    description:
      "Emergency food assistance and nutrition programs providing fresh groceries and meal support for residents in need.",
    shortDescription: "Featured Organization",
    address: "456 Oak Avenue",
    phone: "(206) 555-0101",
    website: "www.cityfoodbank.org",
    image: "/placeholder.svg?key=carousel2",
    tags: ["Food", "Free", "Emergency"],
    ageGroups: ["Families", "Seniors"],
    hours: "Mon-Sat 9am-5pm",
    whyImportant:
      "Distributed over 2 million meals last year and serves as a critical resource for food-insecure families in our community.",
  },
  {
    id: "3",
    name: "Community Mental Health Services",
    category: "Mental Health",
    description:
      "Professional counseling, therapy, and crisis support services available for all ages with sliding scale fees.",
    shortDescription: "Upcoming Event Highlight",
    address: "789 Pine Street",
    phone: "(206) 555-0102",
    website: "www.cmhs.org",
    image: "/placeholder.svg?key=carousel3",
    tags: ["Mental Health", "Counseling", "Support"],
    ageGroups: ["Teens", "Families", "Seniors"],
    hours: "Mon-Fri 8am-6pm, Sat 10am-4pm",
    whyImportant:
      "Expanded their services this year to include peer support groups and crisis hotline available 24/7 for emergencies.",
  },
]
